name: CI-CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install API requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.api.txt -r requirements.test.txt
          pip install pytest flake8
          pip install -e .

      - name: Lint
        run: flake8 .

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
          # Point tests at your host MLflow server substitute (not required for unit tests here)
          MLFLOW_TRACKING_URI: http://localhost:9999
          MLFLOW_REGISTRY_URI: http://localhost:9999
        run: pytest -q

  docker:
    needs: test-and-lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            shekaibbits/mlops-assignment:latest
            shekaibbits/mlops-assignment:${{ github.sha }}
